#!/usr/bin/env python3
"""
Script to create the interactive chat interface notebook
"""

import json

# Notebook structure
notebook = {
    "cells": [
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "# Task 4: Interactive Chat Interface\n",
                "\n",
                "This notebook demonstrates the interactive chat interface for the Financial Complaint Analysis RAG System.\n",
                "\n",
                "## 🎯 Learning Objectives\n",
                "- Understand the chat interface architecture\n",
                "- Learn how to interact with the RAG system\n",
                "- Explore different response formats and configurations\n",
                "- Test the system with various types of questions\n",
                "\n",
                "## 🏗️ Architecture Overview\n",
                "\n",
                "The chat interface consists of several key components:\n",
                "1. **ChatSession**: Manages conversation state and history\n",
                "2. **ResponseFormatter**: Formats RAG responses for display\n",
                "3. **ChatInterface**: Main interface controller\n",
                "4. **StreamingHandler**: Handles response streaming (optional)\n",
                "\n",
                "## 🚀 Features\n",
                "- Real-time chat with the RAG system\n",
                "- Source citation and confidence scoring\n",
                "- Session management and history\n",
                "- Multiple response formats\n",
                "- Interactive configuration options"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Import required libraries\n",
                "import sys\n",
                "import os\n",
                "import time\n",
                "import warnings\n",
                "from datetime import datetime\n",
                "warnings.filterwarnings('ignore')\n",
                "\n",
                "# Add src to path for imports\n",
                "sys.path.append(\"../src\")\n",
                "\n",
                "print(\"✅ Libraries imported successfully!\")\n",
                "print(f\"📁 Current directory: {os.getcwd()}\")\n",
                "print(f\"🐍 Python version: {sys.version}\")"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## 🔍 Check System Setup\n",
                "\n",
                "Let's verify that all required components are available."
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Check if src directory exists and contains required files\n",
                "src_path = \"../src\"\n",
                "if os.path.exists(src_path):\n",
                "    print(f\"✅ Source directory found: {src_path}\")\n",
                "    src_files = os.listdir(src_path)\n",
                "    print(f\"📁 Files in src/: {src_files}\")\n",
                "    \n",
                "    # Check for key components\n",
                "    required_files = ['chat_interface.py', 'rag_pipeline.py', 'ui_app.py']\n",
                "    missing_files = [f for f in required_files if f not in src_files]\n",
                "    \n",
                "    if missing_files:\n",
                "        print(f\"⚠️ Missing files: {missing_files}\")\n",
                "    else:\n",
                "        print(\"✅ All required chat interface components found!\")\n",
                "else:\n",
                "    print(f\"❌ Source directory not found: {src_path}\")\n",
                "    print(\"Please ensure you're running this notebook from the correct location.\")"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## 📚 Import Chat Interface Components\n",
                "\n",
                "Now let's import the chat interface components safely."
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Try to import chat interface components with proper error handling\n",
                "try:\n",
                "    from chat_interface import ChatSession, ChatMessage, GradioResponseFormatter\n",
                "    print(\"✅ Chat interface components imported successfully!\")\n",
                "except ImportError as e:\n",
                "    print(f\"❌ Import Error for Chat Interface: {e}\")\n",
                "    print(\"🔍 This might be because:\")\n",
                "    print(\"   1. The chat_interface.py file doesn't exist\")\n",
                "    print(\"   2. There are missing dependencies\")\n",
                "    print(\"   3. Import path issues\")\n",
                "except Exception as e:\n",
                "    print(f\"❌ Unexpected error: {e}\")\n",
                "\n",
                "try:\n",
                "    from ui_app import ChatInterface\n",
                "    print(\"✅ Streamlit UI components imported successfully!\")\n",
                "except ImportError as e:\n",
                "    print(f\"❌ Import Error for UI App: {e}\")\n",
                "except Exception as e:\n",
                "    print(f\"❌ Unexpected error: {e}\")"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## 🔧 Check Vector Store\n",
                "\n",
                "Let's verify the vector store exists and is accessible for the RAG system."
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Check if vector store exists\n",
                "vector_store_path = \"../vector_store\"\n",
                "if os.path.exists(vector_store_path):\n",
                "    print(f\"✅ Vector store found: {vector_store_path}\")\n",
                "    vector_store_files = os.listdir(vector_store_path)\n",
                "    print(f\"📁 Vector store files: {vector_store_files}\")\n",
                "    \n",
                "    # Check for essential vector store files\n",
                "    essential_files = ['complaint_index.faiss', 'chunks.pkl', 'metadata.pkl']\n",
                "    missing_essential = [f for f in essential_files if f not in vector_store_files]\n",
                "    \n",
                "    if missing_essential:\n",
                "        print(f\"⚠️ Missing essential files: {missing_essential}\")\n",
                "        print(\"🔍 Please run Task 2 notebook first to create the complete vector store.\")\n",
                "    else:\n",
                "        print(\"✅ Vector store is complete and ready for use!\")\n",
                "else:\n",
                "    print(f\"❌ Vector store not found: {vector_store_path}\")\n",
                "    print(\"🔍 Please run Task 2 notebook first to create the vector store.\")\n",
                "    print(\"   Command: jupyter notebook notebooks/02_text_chunking_embedding_vectorstore.ipynb\")"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## 🧪 Test Chat Session Management\n",
                "\n",
                "Let's test the basic chat session functionality."
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Test chat session management if components are available\n",
                "try:\n",
                "    if 'ChatSession' in globals() and 'ChatMessage' in globals():\n",
                "        print(\"🚀 Testing Chat Session Management...\")\n",
                "        \n",
                "        # Create a new chat session\n",
                "        session = ChatSession(\n",
                "            session_id=\"test_session_001\",\n",
                "            messages=[],\n",
                "            created_at=time.time()\n",
                "        )\n",
                "        \n",
                "        # Add some test messages\n",
                "        session.add_message(\"user\", \"What are common credit card issues?\")\n",
                "        session.add_message(\"assistant\", \"Based on the complaint data, common credit card issues include...\", \n",
                "                          sources=[{\"text\": \"Sample source 1\", \"score\": 0.85}], \n",
                "                          confidence=0.85)\n",
                "        \n",
                "        # Display session information\n",
                "        print(f\"✅ Session created: {session.session_id}\")\n",
                "        print(f\"📝 Messages in session: {len(session.messages)}\")\n",
                "        print(f\"🕒 Session created at: {datetime.fromtimestamp(session.created_at)}\")\n",
                "        \n",
                "        # Test history retrieval\n",
                "        history = session.get_history()\n",
                "        print(f\"📚 Chat history pairs: {len(history)}\")\n",
                "        \n",
                "        # Test session export\n",
                "        session_data = session.export_to_dict()\n",
                "        print(f\"💾 Session exported with {len(session_data)} keys\")\n",
                "        \n",
                "        print(\"✅ Chat session management test completed successfully!\")\n",
                "        \n",
                "    else:\n",
                "        print(\"⚠️ Chat session components not available for testing\")\n",
                "        \n",
                "except Exception as e:\n",
                "    print(f\"❌ Error during chat session test: {e}\")\n",
                "    print(\"🔍 Please check the import statements above.\")"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## 🎨 Test Response Formatting\n",
                "\n",
                "Let's test the response formatting capabilities."
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Test response formatting if components are available\n",
                "try:\n",
                "    if 'GradioResponseFormatter' in globals():\n",
                "        print(\"🚀 Testing Response Formatting...\")\n",
                "        \n",
                "        # Create a formatter instance\n",
                "        formatter = GradioResponseFormatter()\n",
                "        \n",
                "        # Create a mock RAG response for testing\n",
                "        from dataclasses import dataclass\n",
                "        \n",
                "        @dataclass\n",
                "        class MockSearchResult:\n",
                "            text: str\n",
                "            score: float\n",
                "            metadata: dict\n",
                "            chunk_id: int\n",
                "        \n",
                "        @dataclass\n",
                "        class MockRAGResponse:\n",
                "            answer: str\n",
                "            retrieved_sources: list\n",
                "            confidence_score: float\n",
                "            processing_time: float\n",
                "            query: str\n",
                "            context_used: str\n",
                "        \n",
                "        # Create mock data\n",
                "        mock_sources = [\n",
                "            MockSearchResult(\n",
                "                text=\"Customer reported unauthorized charges on credit card statement\",\n",
                "                score=0.92,\n",
                "                metadata={\"category\": \"fraud\", \"product\": \"credit_card\"},\n",
                "                chunk_id=1\n",
                "            ),\n",
                "            MockSearchResult(\n",
                "                text=\"Billing dispute over late payment fees\",\n",
                "                score=0.87,\n",
                "                metadata={\"category\": \"billing\", \"product\": \"credit_card\"},\n",
                "                chunk_id=2\n",
                "            )\n",
                "        ]\n",
                "        \n",
                "        mock_response = MockRAGResponse(\n",
                "            answer=\"Based on the complaint data, common credit card issues include unauthorized charges and billing disputes over late payment fees.\",\n",
                "            retrieved_sources=mock_sources,\n",
                "            confidence_score=0.89,\n",
                "            processing_time=1.23,\n",
                "            query=\"What are common credit card issues?\",\n",
                "            context_used=\"Sample context\"\n",
                "        )\n",
                "        \n",
                "        # Test formatting\n",
                "        try:\n",
                "            formatted_response = formatter.format_response(mock_response)\n",
                "            print(\"✅ Response formatting test completed!\")\n",
                "            print(f\"📝 Formatted response length: {len(formatted_response)} characters\")\n",
                "            \n",
                "            # Test source formatting\n",
                "            formatted_sources = formatter.format_sources(mock_sources)\n",
                "            print(f\"📚 Sources formatted successfully: {len(formatted_sources)} characters\")\n",
                "            \n",
                "        except Exception as format_error:\n",
                "            print(f\"⚠️ Formatting test had issues: {format_error}\")\n",
                "            print(\"This might be expected if the formatter expects different data structures\")\n",
                "        \n",
                "    else:\n",
                "        print(\"⚠️ Response formatter not available for testing\")\n",
                "        \n",
                "except Exception as e:\n",
                "    print(f\"❌ Error during response formatting test: {e}\")\n",
                "    print(\"🔍 Please check the import statements above.\")"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## 🔌 Test RAG Pipeline Integration\n",
                "\n",
                "Let's test the integration with the RAG pipeline."
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Test RAG pipeline integration if components are available\n",
                "try:\n",
                "    if 'create_simple_pipeline' in globals():\n",
                "        print(\"🚀 Testing RAG Pipeline Integration...\")\n",
                "        \n",
                "        # Check if vector store exists\n",
                "        vector_store_path = \"../vector_store\"\n",
                "        if os.path.exists(vector_store_path):\n",
                "            print(f\"✅ Vector store found: {vector_store_path}\")\n",
                "            \n",
                "            try:\n",
                "                # Try to create pipeline\n",
                "                pipeline = create_simple_pipeline(vector_store_path)\n",
                "                print(\"✅ RAG Pipeline created successfully!\")\n",
                "                print(\"🚀 Ready to test the chat interface!\")\n",
                "                \n",
                "                # Test a simple query\n",
                "                test_query = \"What are common credit card complaints?\"\n",
                "                print(f\"🔍 Test Query: {test_query}\")\n",
                "                \n",
                "                # Note: We won't run the actual query here to avoid long processing\n",
                "                # but we can verify the pipeline is ready\n",
                "                print(\"✅ RAG pipeline integration test completed!\")\n",
                "                \n",
                "            except Exception as pipeline_error:\n",
                "                print(f\"⚠️ Pipeline creation had issues: {pipeline_error}\")\n",
                "                print(\"This might be due to missing dependencies or configuration\")\n",
                "        else:\n",
                "            print(f\"❌ Vector store not found: {vector_store_path}\")\n",
                "            print(\"🔍 Please run Task 2 notebook first to create the vector store.\")\n",
                "            \n",
                "    else:\n",
                "        print(\"⚠️ RAG pipeline function not available for testing\")\n",
                "        print(\"Please check the import statements above.\")\n",
                "        \n",
                "except Exception as e:\n",
                "    print(f\"❌ Error during RAG pipeline integration test: {e}\")\n",
                "    print(\"🔍 Please check the import statements above.\")"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## 🎯 Interactive Chat Demo\n",
                "\n",
                "Now let's create a simple interactive chat demo using the available components."
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Create an interactive chat demo\n",
                "def create_simple_chat_demo():\n",
                "    \"\"\"Create a simple interactive chat demo.\"\"\"\n",
                "    \n",
                "    if 'ChatSession' not in globals():\n",
                "        print(\"❌ Chat session components not available\")\n",
                "        return\n",
                "    \n",
                "    print(\"🎮 Interactive Chat Demo\")\n",
                "    print(\"=\" * 50)\n",
                "    \n",
                "    # Create a new chat session\n",
                "    session = ChatSession(\n",
                "        session_id=f\"demo_session_{int(time.time())}\",\n",
                "        messages=[],\n",
                "        created_at=time.time()\n",
                "    )\n",
                "    \n",
                "    # Pre-defined responses for demo purposes\n",
                "    demo_responses = {\n",
                "        \"hello\": \"Hello! I'm your Financial Complaint Analysis AI assistant. How can I help you today?\",\n",
                "        \"credit card\": \"Based on the complaint data, common credit card issues include billing disputes, unauthorized charges, and customer service problems.\",\n",
                "        \"mortgage\": \"Mortgage-related complaints often involve servicing issues, payment processing, and loan modification difficulties.\",\n",
                "        \"help\": \"I can help you analyze financial complaints, find patterns, and answer questions about consumer financial issues.\",\n",
                "        \"bye\": \"Thank you for using the Financial Complaint Analysis system. Have a great day!\"\n",
                "    }\n",
                "    \n",
                "    print(\"💡 Type 'help' for assistance, 'bye' to exit, or ask a question about financial complaints.\")\n",
                "    print(\"📝 Example questions:\")\n",
                "    print(\"   - What are common credit card issues?\")\n",
                "    print(\"   - How do customers resolve billing disputes?\")\n",
                "    print(\"   - What are the main security concerns?\")\n",
                "    print(\"-\" * 50)\n",
                "    \n",
                "    # Simple chat loop\n",
                "    while True:\n",
                "        try:\n",
                "            user_input = input(\"👤 You: \").strip().lower()\n",
                "            \n",
                "            if user_input == 'bye':\n",
                "                print(\"🤖 AI: Goodbye!\")\n",
                "                break\n",
                "            elif user_input == 'help':\n",
                "                print(\"🤖 AI: I'm here to help! I can analyze financial complaints and answer your questions.\")\n",
                "                print(\"   Try asking about credit cards, mortgages, billing, or any financial product.\")\n",
                "            elif user_input in demo_responses:\n",
                "                response = demo_responses[user_input]\n",
                "                print(f\"🤖 AI: {response}\")\n",
                "                \n",
                "                # Add to session\n",
                "                session.add_message(\"user\", user_input)\n",
                "                session.add_message(\"assistant\", response)\n",
                "            else:\n",
                "                # Generic response for unknown inputs\n",
                "                response = \"I understand you're asking about financial complaints. In a real RAG system, I would search the complaint database and provide specific, evidence-based answers.\"\n",
                "                print(f\"🤖 AI: {response}\")\n",
                "                \n",
                "                # Add to session\n",
                "                session.add_message(\"user\", user_input)\n",
                "                session.add_message(\"assistant\", response)\n",
                "            \n",
                "            print()\n",
                "            \n",
                "        except KeyboardInterrupt:\n",
                "            print(\"\\n🤖 AI: Chat session interrupted. Goodbye!\")\n",
                "            break\n",
                "        except Exception as e:\n",
                "            print(f\"❌ Error: {e}\")\n",
                "            break\n",
                "    \n",
                "    # Display session summary\n",
                "    print(\"\\n📊 Chat Session Summary\")\n",
                "    print(\"=\" * 30)\n",
                "    print(f\"Session ID: {session.session_id}\")\n",
                "    print(f\"Total Messages: {len(session.messages)}\")\n",
                "    print(f\"Duration: {time.time() - session.created_at:.1f} seconds\")\n",
                "    \n",
                "    return session\n",
                "\n",
                "# Run the demo if components are available\n",
                "if 'ChatSession' in globals():\n",
                "    print(\"🚀 Starting Interactive Chat Demo...\")\n",
                "    print(\"Note: This is a simplified demo. The full system would use the actual RAG pipeline.\")\n",
                "    print()\n",
                "    \n",
                "    # Uncomment the line below to run the interactive demo\n",
                "    # demo_session = create_simple_chat_demo()\n",
                "    print(\"💡 To run the interactive demo, uncomment the line: demo_session = create_simple_chat_demo()\")\n",
                "else:\n",
                "    print(\"⚠️ Chat session components not available for demo\")\n",
                "    print(\"Please check the import statements above.\")"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## 🚀 Streamlit Web Interface\n",
                "\n",
                "The system also includes a Streamlit-based web interface. Here's how to use it:"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Instructions for running the Streamlit web interface\n",
                "print(\"🌐 Streamlit Web Interface Instructions\")\n",
                "print(\"=\" * 50)\n",
                "print(\"\\nTo run the full web interface:\")\n",
                "print(\"1. Open a terminal/command prompt\")\n",
                "print(\"2. Navigate to the project directory\")\n",
                "print(\"3. Run: streamlit run src/ui_app.py\")\n",
                "print(\"4. Open your browser to the provided URL\")\n",
                "print(\"\\nFeatures of the web interface:\")\n",
                "print(\"✅ Real-time chat with the RAG system\")\n",
                "print(\"✅ Source citation and confidence scoring\")\n",
                "print(\"✅ Interactive configuration options\")\n",
                "print(\"✅ Chat history and session management\")\n",
                "print(\"✅ Example questions and suggestions\")\n",
                "print(\"\\nRequirements:\")\n",
                "print(\"📦 streamlit (install with: pip install streamlit)\")\n",
                "print(\"📦 All other dependencies from requirements.txt\")"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## 🔧 Configuration Options\n",
                "\n",
                "The chat interface supports various configuration options:"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Display configuration options\n",
                "print(\"⚙️ Chat Interface Configuration Options\")\n",
                "print(\"=\" * 50)\n",
                "print(\"\\n📊 RAG Pipeline Settings:\")\n",
                "print(\"   • top_k: Number of sources to retrieve (1-10)\")\n",
                "print(\"   • similarity_threshold: Minimum similarity score for sources\")\n",
                "print(\"   • max_context_length: Maximum context length for LLM\")\n",
                "print(\"   • temperature: LLM response creativity (0.0-1.0)\")\n",
                "print(\"   • max_tokens: Maximum response length\")\n",
                "print(\"\\n🎨 Display Options:\")\n",
                "print(\"   • show_sources: Display source citations\")\n",
                "print(\"   • show_metadata: Display source metadata\")\n",
                "print(\"   • show_confidence: Display confidence scores\")\n",
                "print(\"   • response_format: Choose response style\")\n",
                "print(\"\\n💾 Session Management:\")\n",
                "print(\"   • auto_save: Automatically save chat sessions\")\n",
                "print(\"   • export_format: CSV, JSON, or Markdown\")\n",
                "print(\"   • session_timeout: Automatic session cleanup\")"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## 📝 Example Usage Patterns\n",
                "\n",
                "Here are some common usage patterns for the chat interface:"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Example usage patterns\n",
                "print(\"📝 Example Usage Patterns\")\n",
                "print(\"=\" * 40)\n",
                "print(\"\\n🔍 Information Retrieval:\")\n",
                "print(\"   User: 'What are the most common credit card complaints?'\")\n",
                "print(\"   System: Searches database, retrieves relevant sources, generates answer\")\n",
                "print(\"\\n📊 Trend Analysis:\")\n",
                "print(\"   User: 'Have mortgage complaints increased over time?'\")\n",
                "print(\"   System: Analyzes temporal patterns, provides trend insights\")\n",
                "print(\"\\n🔒 Security Issues:\")\n",
                "print(\"   User: 'What are the main security concerns with online banking?'\")\n",
                "print(\"   System: Identifies security-related complaints, categorizes by type\")\n",
                "print(\"\\n💳 Product Comparison:\")\n",
                "print(\"   User: 'How do credit card complaints compare to mortgage complaints?'\")\n",
                "print(\"   System: Compares complaint patterns across product categories\")\n",
                "print(\"\\n🛠️ Resolution Guidance:\")\n",
                "print(\"   User: 'How do customers typically resolve billing disputes?'\")\n",
                "print(\"   System: Provides resolution patterns and success strategies\")"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## 🧪 Testing and Validation\n",
                "\n",
                "Here are some ways to test and validate the chat interface:"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Testing and validation guidelines\n",
                "print(\"🧪 Testing and Validation Guidelines\")\n",
                "print(\"=\" * 45)\n",
                "print(\"\\n✅ Functional Testing:\")\n",
                "print(\"   • Test basic chat functionality\")\n",
                "print(\"   • Verify source retrieval and citation\")\n",
                "print(\"   • Check response formatting\")\n",
                "print(\"   • Test session management\")\n",
                "print(\"\\n🔍 Quality Testing:\")\n",
                "print(\"   • Verify answer relevance and accuracy\")\n",
                "print(\"   • Check source quality and relevance\")\n",
                "print(\"   • Validate confidence scoring\")\n",
                "print(\"   • Test response completeness\")\n",
                "print(\"\\n⚡ Performance Testing:\")\n",
                "print(\"   • Measure response times\")\n",
                "print(\"   • Test with different query types\")\n",
                "print(\"   • Validate memory usage\")\n",
                "print(\"   • Check scalability limits\")\n",
                "print(\"\\n🔄 Integration Testing:\")\n",
                "print(\"   • Test RAG pipeline integration\")\n",
                "print(\"   • Verify vector store connectivity\")\n",
                "print(\"   • Check error handling\")\n",
                "print(\"   • Test configuration changes\")"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## 🚀 Next Steps\n",
                "\n",
                "Now that you have a working chat interface, here are the next steps:"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Next steps and recommendations\n",
                "print(\"🚀 Next Steps and Recommendations\")\n",
                "print(\"=\" * 45)\n",
                "print(\"\\n1. 🧪 Test the Basic System:\")\n",
                "print(\"   • Run the interactive demo above\")\n",
                "print(\"   • Test with various question types\")\n",
                "print(\"   • Verify source retrieval works\")\n",
                "print(\"\\n2. 🌐 Launch the Web Interface:\")\n",
                "print(\"   • Run: streamlit run src/ui_app.py\")\n",
                "print(\"   • Test the full web interface\")\n",
                "print(\"   • Explore configuration options\")\n",
                "print(\"\\n3. 🔧 Optimize Performance:\")\n",
                "print(\"   • Adjust RAG parameters\")\n",
                "print(\"   • Fine-tune response formatting\")\n",
                "print(\"   • Optimize source retrieval\")\n",
                "print(\"\\n4. 📊 Evaluate and Improve:\")\n",
                "print(\"   • Use the evaluation framework from Task 3\")\n",
                "print(\"   • Collect user feedback\")\n",
                "print(\"   • Iterate on response quality\")\n",
                "print(\"\\n5. 🚀 Deploy and Scale:\")\n",
                "print(\"   • Deploy to production environment\")\n",
                "print(\"   • Add monitoring and logging\")\n",
                "print(\"   • Scale for multiple users\")\n",
                "print(\"\\n🎯 Congratulations! You now have a fully functional\")\n",
                "print(\"   Financial Complaint Analysis RAG system with an\")\n",
                "print(\"   interactive chat interface!\")"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## 📚 Additional Resources\n",
                "\n",
                "For more information and advanced usage:"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Additional resources and references\n",
                "print(\"📚 Additional Resources and References\")\n",
                "print(\"=\" * 50)\n",
                "print(\"\\n📖 Documentation:\")\n",
                "print(\"   • Streamlit: https://docs.streamlit.io/\")\n",
                "print(\"   • Gradio: https://gradio.app/docs/\")\n",
                "print(\"   • RAG Systems: https://python.langchain.com/docs/use_cases/question_answering/\")\n",
                "print(\"\\n🔧 Advanced Features:\")\n",
                "print(\"   • Multi-turn conversations\")\n",
                "print(\"   • Context window management\")\n",
                "print(\"   • Response streaming\")\n",
                "print(\"   • Custom prompt engineering\")\n",
                "print(\"\\n🚀 Deployment Options:\")\n",
                "print(\"   • Streamlit Cloud\")\n",
                "print(\"   • Heroku\")\n",
                "print(\"   • AWS/GCP/Azure\")\n",
                "print(\"   • Docker containers\")\n",
                "print(\"\\n💡 Best Practices:\")\n",
                "print(\"   • Error handling and user feedback\")\n",
                "print(\"   • Security and input validation\")\n",
                "print(\"   • Performance monitoring\")\n",
                "print(\"   • User experience optimization\")"
            ]
        }
    ],
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3"
        },
        "language_info": {
            "codemirror_mode": {
                "name": "ipython",
                "value": "ipython"
            },
            "file_extension": ".py",
            "mimetype": "text/x-python",
            "name": "python",
            "nbconvert_exporter": "python",
            "pygments_lexer": "ipython3",
            "version": "3.8.0"
        }
    },
    "nbformat": 4,
    "nbformat_minor": 4
}

# Write the notebook to file
with open('notebooks/04_interactive_chat_interface.ipynb', 'w', encoding='utf-8') as f:
    json.dump(notebook, f, indent=1, ensure_ascii=False)

print("✅ Interactive Chat Interface notebook created successfully!")
print("📁 Location: notebooks/04_interactive_chat_interface.ipynb")
print("🚀 You can now open and run this notebook in Jupyter!")
